# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshForward < Formula
  desc "Forward Linux development-host ports to localhost through system OpenSSH"
  homepage "https://github.com/wangnan0916/ssh-forward"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wangnan0916/ssh-forward/releases/download/v0.8.0/ssh-forward_0.8.0_darwin_amd64.tar.gz"
      sha256 "14318b2c8ce53167af0457603979c01a58e4999653bbdc5cf263e80c94d23910"

      define_method(:install) do
        bin.install "ssh-forward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wangnan0916/ssh-forward/releases/download/v0.8.0/ssh-forward_0.8.0_darwin_arm64.tar.gz"
      sha256 "061de6e7a5921719fdda95a52d86eccbf2351ec05b0a516c6e4221f6e9eb17c4"

      define_method(:install) do
        bin.install "ssh-forward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wangnan0916/ssh-forward/releases/download/v0.8.0/ssh-forward_0.8.0_linux_amd64.tar.gz"
      sha256 "203f89ae8f85152362ebfa81b8e8c32e5d064b029684f545b14f7d837e6eba14"
      define_method(:install) do
        bin.install "ssh-forward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wangnan0916/ssh-forward/releases/download/v0.8.0/ssh-forward_0.8.0_linux_arm64.tar.gz"
      sha256 "bd1ec8d0e56df40573087da69f42f556319ca04c6e5fa90d01073c3d47373640"
      define_method(:install) do
        bin.install "ssh-forward"
      end
    end
  end

  test do
    assert_match "ssh-forward #{version}", shell_output("#{bin}/ssh-forward --version")
  end
end
