# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshForward < Formula
  desc "Forward Linux development-host ports to localhost through system OpenSSH"
  homepage "https://github.com/wangnan0916/ssh-forward"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wangnan0916/ssh-forward/releases/download/v0.13.0/ssh-forward_0.13.0_darwin_amd64.tar.gz"
      sha256 "d4145ecdcd602794500d418ef7e87343048169dec3d75b69f00dec611c50e8df"

      define_method(:install) do
        bin.install "ssh-forward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wangnan0916/ssh-forward/releases/download/v0.13.0/ssh-forward_0.13.0_darwin_arm64.tar.gz"
      sha256 "fe278e9fb84dffc4a834eb4df7bf54012043cd2928e82f94c52c15a6a5c1079b"

      define_method(:install) do
        bin.install "ssh-forward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wangnan0916/ssh-forward/releases/download/v0.13.0/ssh-forward_0.13.0_linux_amd64.tar.gz"
      sha256 "d54a2c9d5411dd4464bd8d1291cd736d3a2cfb716595d7b4dcd317deb919059f"
      define_method(:install) do
        bin.install "ssh-forward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wangnan0916/ssh-forward/releases/download/v0.13.0/ssh-forward_0.13.0_linux_arm64.tar.gz"
      sha256 "af9f7f53cb6704cd71052dce61a192a2632b55bc10022766263b1951975b650e"
      define_method(:install) do
        bin.install "ssh-forward"
      end
    end
  end

  test do
    assert_match "ssh-forward #{version}", shell_output("#{bin}/ssh-forward --version")
  end
end
